theme = 'barks'
[params.head]
    author = "Carl Barks"
    custom_css = "<url_to_custom_css_file>"
    description = "Hi, I'm Carl, and this is my website!"
    keywords = ["some", "keywords", "to", "describe", "this"]
